name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: python
          fork: true
          repo-url: adminbigtek/slo-generator
          github-api-url: https://api.github.com
          github-graphql-url: https://api.github.com/graphql
          include-component-in-tag: false
          skip-github-release: false
          skip-github-pull-request: false
          changelog-host: https://github.com
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
