name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi giờ, bạn có thể thay đổi lịch trình theo nhu cầu

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}  # Sử dụng GitHub token để xác thực

      - name: Set up Git
        run: |
          git config user.name "adminbigtek"
          git config user.email "admin@bigtek.vn"

      - name: Add upstream
        run: git remote add upstream https://github.com/google/slo-generator.git
        # Thay "original-owner/original-repo" bằng URL repo gốc

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main
        # Thay "main" bằng nhánh chính của repo gốc nếu khác

      - name: Push changes
        run: git push origin main
        # Thay "main" bằng nhánh chính của repo đã fork nếu khác
