name: Sync Upstream

on:
  schedule:
    - cron: '1 * * * *' # Chạy mỗi giờ
  workflow_dispatch: # Cho phép kích hoạt thủ công

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }} # Sử dụng GitHub Token mặc định

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/google/slo-generator.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push Changes to Fork
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }} # Sử dụng GitHub Token mặc định
